apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-hooks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-hooks
    server: ""
  project: default
  source:
    path: helm-hooks
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
    valueFiles:
      - values/appname-values-staging.yaml
      - values/appname-org-10-values.yaml
