applications:
  wordpress:
    enabled: true
    enableAutoSync: true
    project: staging
    source:
      chart: wordpress
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 11.0.18
  wordpress2:
    enabled: true
    enableAutoSync: true
    project: staging
    releaseName: wordpress2
    source:
      chart: wordpress
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 11.0.18
    valueFiles:
      - values/wordpress-staging.yaml






