apiVersion: v1
kind: Namespace
metadata:
  name: {{ $.Values.default.app.destination.namespace | required (printf "No destination.namespace specified for %s" $key ) }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"