apiVersion: v1
kind: Namespace
metadata:
  name: {{ $.Values.default.app.destination.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    authorization-sidecar-webhook-sidecar-injector: enabled
    istio-injection: enabled
    name: {{ $.Values.default.app.destination.namespace }}
    prometheus: {{ $.Values.default.app.destination.namespace }}
    sidecar-injection: enabled
