apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    authorization-sidecar-webhook-sidecar-injector: enabled
    istio-injection: enabled
    name: {{ $.Values.default.app.destination.namespace | required (printf "No destination.namespace specified for %s" $key ) }}
    prometheus: {{ $.Values.default.app.destination.namespace | required (printf "No destination.namespace specified for %s" $key ) }}
    sidecar-injection: enabled


